package swing;

import javax.swing.*;
import java.awt.*;

public class MainFrame extends JFrame {
    private JPanel mainPanel;
    private JPanel deckList;
    private JPanel decklistList;
    private JPanel decklistItem;
    private JLabel deckNameValue;
    private JLabel duevalue;
    private JButton learn;
    private JButton edit;

    public MainFrame(String title) {
        super(title);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(mainPanel);
        this.pack();
    }



    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        deckList = new JPanel();
        deckList.setLayout(new BorderLayout(0, 0));
        mainPanel.add(deckList, BorderLayout.CENTER);
        decklistList = new JPanel();
        decklistList.setLayout(new BorderLayout(0, 0));
        deckList.add(decklistList, BorderLayout.CENTER);
        decklistItem = new JPanel();
        decklistItem.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        decklistList.add(decklistItem, BorderLayout.CENTER);
        deckNameValue = new JLabel();
        deckNameValue.setText("deckname");
        decklistItem.add(deckNameValue);
        duevalue = new JLabel();
        duevalue.setText("duevalue");
        decklistItem.add(duevalue);
        learn = new JButton();
        learn.setText("Learn");
        decklistItem.add(learn);
        edit = new JButton();
        edit.setText("Edit");
        decklistItem.add(edit);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
